[package]
name = "sudoku"
version = "0.1.0"
authors = ["Daniel Freitas <44594223+danjfreit@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
